# Generated by Django 4.1.6 on 2023-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spectator',
            field=models.BooleanField(default=False, help_text='Designates whether the user can see site content but not interact with it.', verbose_name='spectator'),
        ),
    ]
