# Generated by Django 4.1.7 on 2023-02-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': [models.Func('username', function='pl-PL-x-icu', template='(%(expressions)s) COLLATE "%(function)s"')]},
        ),
    ]
