runtime: python311

env_variables:
  # This setting is used in settings.py to configure your ALLOWED_HOSTS
  # APPENGINE_URL: PROJECT_ID.uc.r.appspot.com
  APPENGINE_URL: https://hyllemath2.lm.r.appspot.com

handlers:
# This configures Google App Engine to serve the files in the app's static directory.
- url: /static
  static_dir: static/
