# Generated by Django 4.1.6 on 2023-03-12 11:33

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user__is_superuser', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='CharacterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionkind', models.CharField(choices=[('1. DEAD', 'DEAD'), ('2. MAIN', 'MAIN'), ('3. CHANGED', 'CHANGED'), ('4. PARTIAL', 'PARTIAL'), ('5. PAST', 'PAST'), ('6. BYPLAYER', 'BYPLAYER')], default='2. MAIN', max_length=15)),
                ('isalive', models.BooleanField(default=True)),
                ('isalterego', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('originname', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.CharField(max_length=200)),
                ('strength', models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('dexterity', models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('endurance', models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('power', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('fullname', 'pl-PL-x-icu'), 'versionkind'],
            },
        ),
        migrations.CreateModel(
            name='CharacterVersionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=50)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('user'), nulls_first=True), 'title'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000000', max_length=50)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstNameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000000', max_length=50)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdirect', models.BooleanField(default=False)),
                ('identifiedwith', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.character')),
                ('characterversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.characterversion')),
            ],
        ),
        migrations.CreateModel(
            name='FirstNameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('parentgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firstnamegroups', to='characters.firstnamegroup')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX'), ('NONE', 'NONE')], default='MALE', max_length=6)),
                ('isarchaic', models.BooleanField(default=False)),
                ('nominative', models.CharField(max_length=50, unique=True)),
                ('genitive', models.CharField(blank=True, max_length=50, null=True)),
                ('meaning', models.TextField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('comments', models.TextField(blank=True, max_length=10000, null=True)),
                ('equivalents', models.ManyToManyField(blank=True, to='characters.firstname')),
                ('firstnamegroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firstnames', to='characters.firstnamegroup')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originatedfirstnames', to='characters.firstname')),
                ('tags', models.ManyToManyField(blank=True, to='characters.firstnametag')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('nominative', 'pl-PL-x-icu')],
            },
        ),
        migrations.CreateModel(
            name='FamilyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominative', models.CharField(max_length=50, unique=True)),
                ('nominative_pl', models.CharField(blank=True, max_length=50)),
                ('genitive', models.CharField(blank=True, max_length=50, null=True)),
                ('genitive_pl', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('comments', models.TextField(blank=True, max_length=10000, null=True)),
                ('familynamegroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familynames', to='characters.familynamegroup')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originatedfamilynames', to='characters.familyname')),
                ('tags', models.ManyToManyField(blank=True, related_name='familynames', to='characters.familynametag')),
            ],
            options={
                'ordering': ['nominative'],
            },
        ),
    ]
