# Generated by Django 4.1.6 on 2023-02-27 15:01

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='CharacterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionkind', models.CharField(choices=[('1. DEAD', 'DEAD'), ('2. MAIN', 'MAIN'), ('3. PAST', 'PAST'), ('4. PARTIAL', 'PARTIAL')], default='2. MAIN', max_length=10)),
                ('isalive', models.BooleanField(default=True)),
                ('isalterego', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('originname', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000, null=True)),
                ('strength', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('dexterity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('endurance', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('power', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('experience', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='CharacterVersionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=50)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('user'), nulls_first=True), 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominative', models.CharField(max_length=50, unique=True)),
                ('nominative_pl', models.CharField(blank=True, max_length=50)),
                ('genitive', models.CharField(blank=True, max_length=50, null=True)),
                ('genitive_pl', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ['nominative'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=50)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('user'), nulls_first=True), 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX'), ('NONE', 'NONE')], default='MALE', max_length=6)),
                ('nominative', models.CharField(max_length=50, unique=True)),
                ('genitive', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ['nominative'],
            },
        ),
        migrations.CreateModel(
            name='FirstNameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FirstNameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=50)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('user'), nulls_first=True), 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdirect', models.BooleanField(default=False)),
                ('identifiedwith', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.character')),
                ('characterversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.characterversion')),
            ],
        ),
    ]
