# Generated by Django 4.1.6 on 2023-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='characterversiontag',
            name='characters__user_id_268335_idx',
        ),
        migrations.RemoveIndex(
            model_name='familyname',
            name='characters__familyn_9f0875_idx',
        ),
        migrations.RemoveIndex(
            model_name='familyname',
            name='characters__origin__3a4f95_idx',
        ),
        migrations.RemoveIndex(
            model_name='familynametag',
            name='characters__user_id_7f7d13_idx',
        ),
        migrations.RemoveIndex(
            model_name='firstname',
            name='characters__firstna_186915_idx',
        ),
        migrations.RemoveIndex(
            model_name='firstname',
            name='characters__origin__e5f98a_idx',
        ),
        migrations.RemoveIndex(
            model_name='firstnametag',
            name='characters__user_id_c399c3_idx',
        ),
        migrations.RemoveField(
            model_name='character',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='versionkind',
            field=models.CharField(choices=[('1. DEAD', 'Dead'), ('2. MAIN', 'Main'), ('3. PAST', 'Past'), ('4. PARTIAL', 'Partial')], default='2. MAIN', max_length=10),
        ),
    ]
