# Generated by Django 4.1.6 on 2023-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
