# Generated by Django 4.1.6 on 2023-02-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firstnametag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstnametags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firstname',
            name='firstnamegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firstnames', to='characters.firstnamegroup'),
        ),
        migrations.AddField(
            model_name='firstname',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originatedfirstnames', to='characters.firstname'),
        ),
        migrations.AddField(
            model_name='firstname',
            name='tags',
            field=models.ManyToManyField(blank=True, to='characters.firstnametag'),
        ),
        migrations.AddField(
            model_name='familynametag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familynametags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyname',
            name='familynamegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familynames', to='characters.familynamegroup'),
        ),
        migrations.AddField(
            model_name='familyname',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originatedfamilynames', to='characters.familyname'),
        ),
        migrations.AddField(
            model_name='familyname',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='familynames', to='characters.familynametag'),
        ),
        migrations.AddField(
            model_name='characterversiontag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characterversiontags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characterversions', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='familyname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.familyname'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='firstname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.firstname'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characterversions', to='resources.picture'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='characterversions', to='characters.characterversiontag'),
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='known_by_characters', through='characters.Relationship', to='characters.characterversion'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('character', 'characterversion')},
        ),
    ]
