# Generated by Django 4.1.7 on 2023-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterversion',
            name='versionkind',
            field=models.CharField(choices=[('1. DEAD', 'DEAD'), ('2. MAIN', 'MAIN'), ('3. CHANGED', 'CHANGED'), ('4. PARTIAL', 'PARTIAL'), ('5. PAST', 'PAST')], default='2. MAIN', max_length=10),
        ),
    ]
