# Generated by Django 4.1.6 on 2023-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['user__is_superuser', 'maincharacterversionname']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='relationships',
        ),
        migrations.AddField(
            model_name='character',
            name='maincharacterversionname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
