# Generated by Django 4.1.6 on 2023-03-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterversion',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
