# Generated by Django 4.1.7 on 2023-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialoguePacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('characters', models.ManyToManyField(to='characters.character')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='dialoguepackets',
            field=models.ManyToManyField(blank=True, to='characters.dialoguepacket'),
        ),
    ]
