# Generated by Django 4.1.6 on 2023-03-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstname',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='firstnames', to='characters.firstnametag'),
        ),
    ]
