# Generated by Django 4.1.7 on 2023-02-28 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myproject.utils_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstnamegroup',
            name='parentgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='characters.firstnamegroup'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=myproject.utils_models.get_gamemaster, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
