# Generated by Django 4.1.7 on 2023-06-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterKnownInfoItemVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('characters.character',),
        ),
    ]
