# Generated by Django 4.1.6 on 2023-02-26 11:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_characterversiontag_characters__user_id_268335_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterversiontag',
            options={'ordering': [models.OrderBy(models.F('user'), nulls_first=True), 'title']},
        ),
        migrations.AlterModelOptions(
            name='familynametag',
            options={'ordering': [models.OrderBy(models.F('user'), nulls_first=True), 'title']},
        ),
        migrations.AlterModelOptions(
            name='firstnametag',
            options={'ordering': [models.OrderBy(models.F('user'), nulls_first=True), 'title']},
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='versionkind',
            field=models.CharField(choices=[('1. DEAD', 'DEAD'), ('2. MAIN', 'MAIN'), ('3. PAST', 'PAST'), ('4. PARTIAL', 'PARTIAL')], default='2. MAIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='firstname',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX'), ('NONE', 'NONE')], default='MALE', max_length=6),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdirect', models.BooleanField(default=False)),
                ('identifiedwith', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.character')),
                ('characterversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.characterversion')),
            ],
            options={
                'unique_together': {('character', 'characterversion')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='acquaintaned_to', through='characters.Relationship', to='characters.characterversion'),
        ),
    ]
