# Generated by Django 4.1.6 on 2023-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterKnownCharacterVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('characters.character',),
        ),
        migrations.CreateModel(
            name='CharacterKnownLocationVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('characters.character',),
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'ordering': ['content_type']},
        ),
        migrations.AddField(
            model_name='characterversion',
            name='frequentedlocations',
            field=models.ManyToManyField(blank=True, related_name='characters', to='locations.location'),
        ),
    ]
