# Generated by Django 4.1.6 on 2023-02-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterversion',
            name='familyname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.familyname'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='firstname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.firstname'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='originname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
