# Generated by Django 4.1.7 on 2023-06-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_dialoguepacket_character_dialoguepackets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterversion',
            old_name='_comment',
            new_name='versioncomment',
        ),
    ]
