# Generated by Django 4.1.7 on 2023-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('characters', '0003_characterknowncharacterversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterversion',
            name='frequentedlocations',
        ),
        migrations.AddField(
            model_name='characterversion',
            name='frequentedlocationversions',
            field=models.ManyToManyField(blank=True, related_name='characters', to='locations.locationversion'),
        ),
    ]
