# Generated by Django 4.1.7 on 2023-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_characterversion_versionkind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['user__is_superuser', 'user__username']},
        ),
        migrations.AddField(
            model_name='familyname',
            name='comments',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='firstname',
            name='comments',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='firstname',
            name='equivalents',
            field=models.ManyToManyField(blank=True, to='characters.firstname'),
        ),
        migrations.AddField(
            model_name='firstname',
            name='isarchaic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firstname',
            name='meaning',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
