# Generated by Django 4.1.6 on 2023-03-17 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_firstname_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterversion',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='characterversion',
            name='endurance',
        ),
        migrations.RemoveField(
            model_name='characterversion',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='characterversion',
            name='power',
        ),
        migrations.RemoveField(
            model_name='characterversion',
            name='strength',
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='character',
            name='endurance',
            field=models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='power',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
