# Generated by Django 4.1.6 on 2023-03-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['user__is_superuser', 'mainversionname']},
        ),
        migrations.RenameField(
            model_name='character',
            old_name='maincharacterversionname',
            new_name='mainversionname',
        ),
    ]
