# Generated by Django 4.1.7 on 2023-02-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_firstnamegroup_parentgroup_alter_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstnamegroup',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='firstnamegroup',
            unique_together={('title', 'parentgroup')},
        ),
    ]
