# Generated by Django 4.1.6 on 2023-02-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_characterversiontag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='known_by_characters', through='characters.Relationship', to='characters.characterversion'),
        ),
    ]
