# Generated by Django 4.1.6 on 2023-03-17 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_characterversion_dexterity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='power',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
