# Generated by Django 4.1.7 on 2023-06-12 18:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_remove_infoitemversion_unique_infoitemversion_infoitem_versionkind_and_more'),
        ('characters', '0004_alter_characterknowncharacterversion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterversion',
            options={'ordering': ['versionkind', django.db.models.functions.comparison.Collate('fullname', 'pl-PL-x-icu')]},
        ),
        migrations.AddField(
            model_name='characterversion',
            name='infopacketset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infos.infopacketset'),
        ),
    ]
