# Generated by Django 4.1.7 on 2023-03-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
