# Generated by Django 4.1.7 on 2023-02-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_firstnamegroup_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familynametag',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='firstnametag',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='familynametag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='firstnametag',
            name='user',
        ),
    ]
