# Generated by Django 4.1.6 on 2023-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_characterversion_frequentedlocations_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='characterversion',
            constraint=models.UniqueConstraint(condition=models.Q(('versionkind', '2. MAIN')), fields=('character', 'versionkind'), name='unique_character_for_mainversion'),
        ),
    ]
