# Generated by Django 4.1.7 on 2023-02-28 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0005_alter_familynametag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familynametag',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='firstnametag',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='characterversiontag',
            unique_together={('title', 'user')},
        ),
    ]
