# Generated by Django 4.1.6 on 2023-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_characterversion_unique_character_for_mainversion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='characterversion',
            name='unique_character_for_mainversion',
        ),
        migrations.AlterUniqueTogether(
            name='characterversion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='characterversion',
            constraint=models.UniqueConstraint(fields=('character', 'picture', 'versionkind', 'fullname'), name='unique_characterversion_character_picture_versionkind_fullname'),
        ),
        migrations.AddConstraint(
            model_name='characterversion',
            constraint=models.UniqueConstraint(condition=models.Q(('versionkind', '2. MAIN')), fields=('character',), name='unique_characterversion_main'),
        ),
    ]
