# Generated by Django 4.1.6 on 2023-03-19 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0005_alter_character_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterversion',
            name='_createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characterversionscreated', to='characters.character'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('user', '_mainversionname')},
        ),
    ]
