# Generated by Django 4.1.7 on 2023-03-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_delete_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['user__is_superuser', '_mainversionname']},
        ),
        migrations.RenameField(
            model_name='character',
            old_name='mainversionname',
            new_name='_mainversionname',
        ),
    ]
