# Generated by Django 4.1.6 on 2023-03-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_characterversion__createdby_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set(),
        ),
    ]
