# Generated by Django 4.1.7 on 2023-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_characterversion_unique_character_for_mainversion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='characterversion',
            name='unique_characterversion_character_picture_versionkind_fullname',
        ),
        migrations.AddConstraint(
            model_name='characterversion',
            constraint=models.UniqueConstraint(fields=('character', 'versionkind', 'picture', 'fullname'), name='unique_characterversion_character_versionkind_picture_fullname'),
        ),
    ]
