# Generated by Django 4.1.7 on 2023-06-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_characterversion_unique_characterversion_character_picture_versionkind_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterversion',
            name='_createdby',
        ),
        migrations.AddField(
            model_name='character',
            name='_createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characterversionscreated', to='characters.character'),
        ),
    ]
