# Generated by Django 4.1.7 on 2023-06-04 17:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_mainversionname', models.CharField(blank=True, max_length=150, null=True)),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['_mainversionname'],
            },
        ),
        migrations.CreateModel(
            name='LocationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominative', models.CharField(max_length=100)),
                ('genitive', models.CharField(blank=True, max_length=100, null=True)),
                ('adjectiveroot', models.CharField(blank=True, max_length=100, null=True)),
                ('equivalents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('nominative', 'pl-PL-x-icu')],
            },
        ),
        migrations.CreateModel(
            name='LocationNameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000000', max_length=50)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('ordernum', models.IntegerField()),
            ],
            options={
                'ordering': ['ordernum'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('namepl', models.CharField(blank=True, max_length=100, null=True)),
                ('hierarchynum', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['hierarchynum'],
            },
        ),
        migrations.CreateModel(
            name='LocationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionkind', models.CharField(choices=[('1. MAIN', 'MAIN'), ('2. PARTIAL', 'PARTIAL'), ('3. PAST', 'PAST'), ('4. BYPLAYER', 'BYPLAYER')], default='1. MAIN', max_length=15)),
                ('descriptivename', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
                ('_comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locationversions', to='locations.location')),
            ],
            options={
                'ordering': ['location', '-_createdat'],
            },
        ),
    ]
