# Generated by Django 4.1.7 on 2023-03-13 16:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToponymTag',
            new_name='LocationNameTag',
        ),
        migrations.CreateModel(
            name='LocationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominative', models.CharField(max_length=100, unique=True)),
                ('genitive', models.CharField(blank=True, max_length=100, null=True)),
                ('equivalents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('meaning', models.TextField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('locationnametags', models.ManyToManyField(related_name='locationnames', to='locations.locationnametag')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('nominative', 'pl-PL-x-icu')],
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.locationname'),
        ),
        migrations.DeleteModel(
            name='Toponym',
        ),
    ]
