# Generated by Django 4.1.6 on 2023-03-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationname',
            old_name='locationnametags',
            new_name='tags',
        ),
    ]
