# Generated by Django 4.1.7 on 2023-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locationversion',
            constraint=models.UniqueConstraint(fields=('location', 'versionkind', 'picture', 'propername', 'descriptivename'), name='unique_locationversion_location_versionkind_picture_propername_descriptivename'),
        ),
        migrations.AddConstraint(
            model_name='locationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('versionkind', '1. MAIN')), fields=('location',), name='unique_locationversion_main'),
        ),
    ]
