# Generated by Django 4.1.6 on 2023-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_locationnametags_locationname_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationversion',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
