# Generated by Django 4.1.7 on 2023-06-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_remove_infoitemversion_unique_infoitemversion_infoitem_versionkind_and_more'),
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationversion',
            name='infopacketset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infos.infopacketset'),
        ),
    ]
