# Generated by Django 4.1.7 on 2023-06-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_remove_characterversion__createdby_and_more'),
        ('locations', '0002_locationversion_unique_locationversion_location_versionkind_picture_propername_descriptivename_and_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationversion',
            name='_createdby',
        ),
        migrations.AddField(
            model_name='location',
            name='_createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='createdlocations', to='characters.character'),
        ),
    ]
