# Generated by Django 4.1.7 on 2023-06-04 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enigmalevel', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
                ('_createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infoitemscreated', to='characters.character')),
            ],
            options={
                'ordering': ['enigmalevel', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InfoPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('infoitems', models.ManyToManyField(help_text='<span style="color:red;font-size:1.2rem;">❖ InfoItems of the same Enigma Level!</span><br>', related_name='infopackets', to='infos.infoitem')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('title', 'pl-PL-x-icu')],
            },
        ),
        migrations.CreateModel(
            name='InfoPacketKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locationordering', models.IntegerField(blank=True, null=True)),
                ('characterordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['locationordering', 'characterordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InfoPacketSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('infopackets', models.ManyToManyField(related_name='infopacketsets', to='infos.infopacket')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('title', 'pl-PL-x-icu')],
            },
        ),
        migrations.AddField(
            model_name='infopacket',
            name='infopacketkinds',
            field=models.ManyToManyField(related_name='infopackets', to='infos.infopacketkind'),
        ),
        migrations.AddField(
            model_name='infopacket',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='infopackets', to='infos.reference'),
        ),
        migrations.CreateModel(
            name='InfoItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionkind', models.CharField(choices=[('1. MAIN', 'MAIN'), ('2. PARTIAL', 'PARTIAL'), ('3. PAST', 'PAST'), ('4. BYPLAYER', 'BYPLAYER')], default='1. MAIN', max_length=15)),
                ('text', models.TextField()),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
                ('infoitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infoitemversions', to='infos.infoitem')),
            ],
            options={
                'ordering': ['infoitem', 'versionkind'],
            },
        ),
        migrations.AddConstraint(
            model_name='infoitemversion',
            constraint=models.UniqueConstraint(fields=('infoitem', 'text', 'versionkind'), name='unique_infoitemversion_infoitem_versionkind'),
        ),
        migrations.AddConstraint(
            model_name='infoitemversion',
            constraint=models.UniqueConstraint(condition=models.Q(('versionkind', '1. MAIN')), fields=('infoitem',), name='unique_infoitemversion_main'),
        ),
    ]
