# Generated by Django 4.1.7 on 2023-06-10 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enigmalevel', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('isrestricted', models.BooleanField(default=True)),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
                ('_createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infoitemscreated', to='characters.character')),
            ],
            options={
                'ordering': ['enigmalevel', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InfoItemPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
                ('infoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionsininfopackets', to='infos.infoitem')),
            ],
            options={
                'ordering': ['infopacket', 'infoitem', 'position'],
            },
        ),
        migrations.CreateModel(
            name='InfoPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infopacketkind', models.CharField(choices=[('000. TEMP-GENERAL', 'TEMP-GENERAL'), ('101. LOC-GEOGRAPHY', 'LOC-GEOGRAPHY'), ('102. LOC-BIOLOGY', 'LOC-BIOLOGY'), ('103. LOC-ECONOMICS', 'LOC-ECONOMICS'), ('201. CHA-BIOGRAPHY', 'CHA-BIOGRAPHY'), ('202. CHA-SECRETS', 'CHA-SECRETS')], default='000. TEMP-GENERAL', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('infoitems', models.ManyToManyField(related_name='infopackets', through='infos.InfoItemPosition', to='infos.infoitem')),
            ],
            options={
                'ordering': ['infopacketkind', django.db.models.functions.comparison.Collate('title', 'pl-PL-x-icu')],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InfoPacketSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('infopackets', models.ManyToManyField(related_name='infopacketsets', to='infos.infopacket')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('title', 'pl-PL-x-icu')],
            },
        ),
        migrations.CreateModel(
            name='InfoItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionkind', models.CharField(choices=[('1. MAIN', 'MAIN'), ('2. PARTIAL', 'PARTIAL'), ('3. PAST', 'PAST'), ('4. BYPLAYER', 'BYPLAYER')], default='1. MAIN', max_length=15)),
                ('text', models.TextField()),
                ('_createdat', models.DateTimeField(auto_now_add=True)),
                ('infoitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infoitemversions', to='infos.infoitem')),
                ('references', models.ManyToManyField(blank=True, related_name='infoitems', to='infos.reference')),
            ],
            options={
                'ordering': ['infoitem', 'versionkind'],
            },
        ),
        migrations.AddField(
            model_name='infoitemposition',
            name='infopacket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoitempositions', to='infos.infopacket'),
        ),
        migrations.AddConstraint(
            model_name='infoitemversion',
            constraint=models.UniqueConstraint(fields=('infoitem', 'text', 'versionkind'), name='unique_infoitemversion_infoitem_versionkind'),
        ),
        migrations.AddConstraint(
            model_name='infoitemversion',
            constraint=models.UniqueConstraint(condition=models.Q(('versionkind', '1. MAIN')), fields=('infoitem',), name='unique_infoitemversion_main'),
        ),
        migrations.AlterUniqueTogether(
            name='infoitemposition',
            unique_together={('infopacket', 'infoitem')},
        ),
    ]
