# Generated by Django 4.1.7 on 2023-03-24 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0006_remove_characterversion_unique_character_for_mainversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('infopacketkind', models.CharField(choices=[('1. KNOWLEDGE', 'KNOWLEDGE'), ('2. BIOGRAPHY', 'BIOGRAPHY'), ('3. DIALOGUE', 'DIALOGUE')], default='1. KNOWLEDGE', max_length=15)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infopacketsauthored', to='characters.character')),
                ('informees', models.ManyToManyField(blank=True, related_name='infopackets', to='characters.character')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('title', 'pl-PL-x-icu'), 'infopacketkind'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InfoPacketPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdum', models.IntegerField()),
                ('contained_infopacket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containing_infopackets', to='infos.infopacket')),
                ('containing_infopacket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_infopackets', to='infos.infopacket')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('containing_infopacket__title', 'pl-PL-x-icu')],
                'unique_together': {('containing_infopacket', 'contained_infopacket')},
            },
        ),
        migrations.AddField(
            model_name='infopacket',
            name='ininfopackets',
            field=models.ManyToManyField(blank=True, related_name='infopackets', through='infos.InfoPacketPosition', to='infos.infopacket'),
        ),
        migrations.AddField(
            model_name='infopacket',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='infopackets', to='infos.reference'),
        ),
    ]
