# Generated by Django 4.1.7 on 2023-06-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoitem',
            name='isrestricted',
            field=models.BooleanField(default=True),
        ),
    ]
