# Generated by Django 4.1.7 on 2023-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_infoitemversion_versioncomment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoitemposition',
            options={'ordering': ['infopacket', 'position']},
        ),
        migrations.AlterField(
            model_name='infopacket',
            name='infopacketkind',
            field=models.CharField(choices=[('TEMP-0-GENERAL', 'TEMP-0-GENERAL'), ('CHA-1-BIOGRAPHY', 'CHA-1-BIOGRAPHY'), ('CHA-2-SECRETS', 'CHA-2-SECRETS'), ('LOC-1-GEOGRAPHY', 'LOC-1-GEOGRAPHY'), ('LOC-2-BIOLOGY', 'LOC-2-BIOLOGY'), ('LOC-3-ECONOMICS', 'LOC-3-ECONOMICS')], default='TEMP-0-GENERAL', max_length=100),
        ),
    ]
