# Generated by Django 4.1.7 on 2023-06-04 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_characterversion_unique_character_for_mainversion_and_more'),
        ('infos', '0002_infoitem_infoitemversion_infopacketkind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoitemversion',
            options={'ordering': ['infoitem', 'versionkind', 'title']},
        ),
        migrations.RemoveField(
            model_name='infoitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='infoitemversion',
            name='_comment',
        ),
        migrations.RemoveField(
            model_name='infoitemversion',
            name='_createdby',
        ),
        migrations.AddField(
            model_name='infoitem',
            name='_createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infoitemscreated', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='infoitem',
            name='enigmalevel',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='infopacket',
            name='infoitems',
            field=models.ManyToManyField(related_name='infopackets', to='infos.infoitem'),
        ),
        migrations.AlterField(
            model_name='infopacket',
            name='infopacketkinds',
            field=models.ManyToManyField(related_name='infopackets', to='infos.infopacketkind'),
        ),
        migrations.CreateModel(
            name='InfoPacketSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('infopackets', models.ManyToManyField(related_name='infopacketsets', to='infos.infopacket')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('title', 'pl-PL-x-icu')],
            },
        ),
    ]
