# Generated by Django 4.1.7 on 2023-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_alter_infoitemversion_options_remove_infoitem_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoitem',
            options={'ordering': ['enigmalevel', 'title']},
        ),
        migrations.AlterModelOptions(
            name='infoitemversion',
            options={'ordering': ['infoitem', 'versionkind']},
        ),
        migrations.RemoveField(
            model_name='infoitem',
            name='_mainversiontitle',
        ),
        migrations.RemoveField(
            model_name='infoitemversion',
            name='title',
        ),
        migrations.AddField(
            model_name='infoitem',
            name='title',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
    ]
