# Generated by Django 4.1.7 on 2023-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_alter_infoitem_options_alter_infoitemversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopacket',
            name='infoitems',
            field=models.ManyToManyField(help_text='<span style="color:red;font-size:1.2rem;">❖ InfoItems of the same Enigma Level!</span><br>', related_name='infopackets', to='infos.infoitem'),
        ),
        migrations.AddConstraint(
            model_name='infoitemversion',
            constraint=models.UniqueConstraint(fields=('infoitem', 'text', 'versionkind'), name='unique_infoitemversion_infoitem_versionkind'),
        ),
        migrations.AddConstraint(
            model_name='infoitemversion',
            constraint=models.UniqueConstraint(condition=models.Q(('versionkind', '1. MAIN')), fields=('infoitem',), name='unique_infoitemversion_main'),
        ),
    ]
