# Generated by Django 4.1.7 on 2023-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_remove_infoitemversion_unique_infoitemversion_infoitem_versionkind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopacketset',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='infoitemposition',
            unique_together={('infoitem', 'infopacket')},
        ),
    ]
