# Generated by Django 4.1.7 on 2023-06-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_alter_infopacketset_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopacket',
            options={},
        ),
        migrations.RemoveField(
            model_name='infopacket',
            name='infopacketkind',
        ),
    ]
