# Generated by Django 4.1.7 on 2023-06-15 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0006_alter_infopacket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPacketKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='infopacket',
            options={'ordering': ['infopacketkind', django.db.models.functions.comparison.Collate('title', 'pl-PL-x-icu')]},
        ),
        migrations.AddField(
            model_name='infopacket',
            name='infopacketkind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='infos.infopacketkind'),
            preserve_default=False,
        ),
    ]
