# Generated by Django 4.1.6 on 2023-03-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureversion',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictureversions', to='resources.picture'),
        ),
    ]
