# Generated by Django 4.1.7 on 2023-03-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureVersionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.IntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictureversions', to='contenttypes.contenttype')),
                ('pictureversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictureversionpositions', to='resources.pictureversion')),
            ],
            options={
                'ordering': ['content_type'],
            },
        ),
        migrations.AddIndex(
            model_name='pictureversionposition',
            index=models.Index(fields=['content_type', 'object_id'], name='resources_p_content_364731_idx'),
        ),
    ]
