# Generated by Django 4.1.7 on 2023-06-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_pictureposition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictureposition',
            options={'ordering': ['content_type', 'position', 'picture']},
        ),
    ]
