# Generated by Django 4.1.7 on 2023-06-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_pictureversionposition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictureversionposition',
            options={'ordering': ['content_type', 'pictureversion', 'position']},
        ),
    ]
